=== mohan252/billing_app/ReportsConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 sp1 (http://www.altova.com) by mthiru (EMBRACE) -->
<!--W3C Schema generated by XMLSpy v2007 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ReportConfiguration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Report" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Report">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ChartType" type="ChartType" maxOccurs="unbounded"/>
				<xs:element ref="Data"/>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Filters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Filter" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Query">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="Name" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Filter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Query" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
			<xs:attribute name="FilterValueType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="List"/>
						<xs:enumeration value="Query"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="FilterValueQuery" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Data">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Query"/>
			</xs:sequence>
			<xs:attribute name="FilterDescription" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ChartType">
		<xs:sequence>
			<xs:element ref="Filters" minOccurs="0"/>
			<xs:element name="ChartType" type="ChartType" minOccurs="0"/>
			<xs:element name="Parent" type="ChartType" minOccurs="0"/>
			<xs:element ref="Query" minOccurs="0"/>
			<xs:element ref="Data" minOccurs="0"/>
			<xs:element name="Tag" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="Name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="BarChart"/>
					<xs:enumeration value="PieChart"/>
					<xs:enumeration value="LineChart"/>
					<xs:enumeration value="DataGrid"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Description" type="xs:string" use="optional"/>
		<xs:attribute name="ShowXAxisLabel" type="xs:boolean"/>
		<xs:attribute name="ShowYAxisLabel" type="xs:boolean"/>
	</xs:complexType>
</xs:schema>

=== mohan252/billing_app/ReportsConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 (http://www.altova.com) by Mohan (kumudam) -->
<ReportConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\personal\Projects\BillingApplication\ReportsConfig.xsd">
	<Report Name="TurnOverByParty">
		<ChartType Name="BarChart">
			<Filters>
				<Filter Name="Amount Rank" FilterValueType="List">
					<Query Name="Top 5">SELECT TOP 5 [NAME] AS PARTY , SUM(BALANCE) AS TURNOVER FROM BILLSTBL INNER JOIN PARTIES ON PARTYID = ID GROUP BY [NAME] ORDER BY SUM(BALANCE) DESC</Query>
					<Query Name="Top 10">SELECT TOP 10 [NAME] AS PARTY , SUM(BALANCE) AS TURNOVER FROM BILLSTBL INNER JOIN PARTIES ON PARTYID = ID GROUP BY [NAME] ORDER BY SUM(BALANCE) DESC</Query>
					<Query Name="Top 15">SELECT TOP 15 [NAME] AS PARTY , SUM(BALANCE) AS TURNOVER FROM BILLSTBL INNER JOIN PARTIES ON PARTYID = ID GROUP BY [NAME] ORDER BY SUM(BALANCE) DESC</Query>
					<Query Name="Bottom 15">SELECT TOP 15 [NAME] AS PARTY , SUM(BALANCE) AS TURNOVER FROM BILLSTBL INNER JOIN PARTIES ON PARTYID = ID GROUP BY [NAME] ORDER BY SUM(BALANCE)</Query>
				</Filter>
				<Filter Name="Party" FilterValueType="Query" FilterValueQuery="select distinct name from parties where id in (select partyid from bills)">
					<Query>SELECT '$VALUE',SUM(BALANCE) AS AMOUNT FROM BILLSTBL
WHERE PARTYID IN (SELECT ID FROM PARTIES WHERE NAME = '$VALUE')
GROUP BY PARTYID</Query>
				</Filter>
			</Filters>
			<ChartType Name="DataGrid" Description="TurnOver by Party : $KEY1">
				<Data>
					<Query>SELECT BILLNO,CONVERT(VARCHAR,BILLDATE,7) AS BILLDATE,BALANCE,AGENT FROM BILLSTBL INNER JOIN PARTIES ON PARTYID = ID WHERE NAME = '$KEY1'</Query>
				</Data>
			</ChartType>
		</ChartType>
		<ChartType Name="PieChart">
			<Filters>
				<Filter Name="Amount Rank" FilterValueType="List">
					<Query Name="Top 5">SELECT * FROM
(SELECT TOP 5 [NAME] AS PARTY , SUM(BALANCE) AS TURNOVER FROM BILLSTBL INNER JOIN PARTIES ON PARTYID = ID GROUP BY [NAME] ORDER BY SUM(BALANCE) DESC) as p1 
UNION
SELECT * FROM
(SELECT 'OTHERS' AS PARTY, SUM(BALANCE) AS BALANCE FROM BILLSTBL
WHERE BILLSTBL.PARTYID NOT IN(
SELECT t12.PARTYID FROM (
SELECT TOP 5 PARTYID,SUM(BALANCE) AS BALANCE FROM BILLSTBL GROUP BY PARTYID ORDER BY SUM(BALANCE) DESC) as t12)) as p2</Query>
					<Query Name="Top 10">SELECT * FROM
(SELECT TOP 10 [NAME] AS PARTY , SUM(BALANCE) AS TURNOVER FROM BILLSTBL INNER JOIN PARTIES ON PARTYID = ID GROUP BY [NAME] ORDER BY SUM(BALANCE) DESC) as p1 
UNION
SELECT * FROM
(SELECT 'OTHERS' AS PARTY, SUM(BALANCE) AS BALANCE FROM BILLSTBL
WHERE BILLSTBL.PARTYID NOT IN(
SELECT t12.PARTYID FROM (
SELECT TOP 10 PARTYID,SUM(BALANCE) AS BALANCE FROM BILLSTBL GROUP BY PARTYID ORDER BY SUM(BALANCE) DESC) as t12)) as p2</Query>
					<Query Name="Top 15">SELECT * FROM
(SELECT TOP 15 [NAME] AS PARTY , SUM(BALANCE) AS TURNOVER FROM BILLSTBL INNER JOIN PARTIES ON PARTYID = ID GROUP BY [NAME] ORDER BY SUM(BALANCE) DESC) as p1 
UNION
SELECT * FROM
(SELECT 'OTHERS' AS PARTY, SUM(BALANCE) AS BALANCE FROM BILLSTBL
WHERE BILLSTBL.PARTYID NOT IN(
SELECT t12.PARTYID FROM (
SELECT TOP 15 PARTYID,SUM(BALANCE) AS BALANCE FROM BILLSTBL GROUP BY PARTYID ORDER BY SUM(BALANCE) DESC) as t12)) as p2</Query>
					<Query Name="Bottom 15">SELECT * FROM
(SELECT TOP 5 [NAME] AS PARTY , SUM(BALANCE) AS TURNOVER FROM BILLSTBL INNER JOIN PARTIES ON PARTYID = ID GROUP BY [NAME] ORDER BY SUM(BALANCE)) as p1 
UNION
SELECT * FROM
(SELECT 'OTHERS' AS PARTY, SUM(BALANCE) AS BALANCE FROM BILLSTBL
WHERE BILLSTBL.PARTYID NOT IN(
SELECT t12.PARTYID FROM (
SELECT TOP 5 PARTYID,SUM(BALANCE) AS BALANCE FROM BILLSTBL GROUP BY PARTYID ORDER BY SUM(BALANCE)) as t12)) as p2</Query>
				</Filter>
				<Filter Name="Party" FilterValueType="Query" FilterValueQuery="select distinct name from parties where id in (select partyid from bills)">
					<Query>SELECT * FROM
(SELECT [NAME] AS PARTY,SUM(BALANCE) AS BALANCE FROM BILLS INNER JOIN PARTIES ON PARTYID = ID WHERE [NAME] = '$VALUE' GROUP BY [NAME]) AS P1
UNION
SELECT * FROM
(SELECT 'OTHERS' AS PARTY, SUM(BALANCE) AS BALANCE FROM BILLS
WHERE BILLSTBL.PARTYID NOT IN (SELECT ID FROM PARTIES WHERE [NAME] = '$VALUE')
) AS P2</Query>
				</Filter>
			</Filters>
		</ChartType>
		<Data FilterDescription="Party wise turn over (increasing order)">
			<Query>SELECT [NAME] AS PARTY , SUM(BALANCE) AS TURNOVER FROM BILLSTBL INNER JOIN PARTIES ON PARTYID = ID GROUP BY [NAME] ORDER BY SUM(BALANCE) DESC</Query>
		</Data>
	</Report>
	<Report Name="TurnOverByAgent">
		<ChartType Name="BarChart">
			<Filters>
				<Filter Name="Amount Rank" FilterValueType="List">
					<Query Name="Top">SELECT AGENT,SUM(BALANCE) AS TURNOVER FROM BILLSTBL GROUP BY AGENT ORDER BY SUM(BALANCE) DESC</Query>
					<Query Name="Bottom">SELECT AGENT,SUM(BALANCE) AS TURNOVER FROM BILLSTBL GROUP BY AGENT ORDER BY SUM(BALANCE)</Query>
				</Filter>
				<Filter Name="Agent" FilterValueType="Query" FilterValueQuery="select distinct name from agents where name in (select agent from bills)">
					<Query>SELECT '$VALUE',SUM(BALANCE) AS AMOUNT FROM BILLSTBL
WHERE AGENT = '$VALUE'
GROUP BY AGENT</Query>
				</Filter>
			</Filters>
			<ChartType Name="DataGrid" Description="TurnOver by Agent : $KEY1">
				<Data>
					<Query>SELECT BILLNO,CONVERT(VARCHAR,BILLDATE,7) AS BILLDATE,[NAME] AS PARTY,BALANCE FROM BILLSTBL INNER JOIN PARTIES ON PARTYID = ID WHERE AGENT = '$KEY1'</Query>
				</Data>
			</ChartType>
		</ChartType>
		<ChartType Name="PieChart">
			<Filters>
				<Filter Name="Amount Rank" FilterValueType="List">
					<Query Name="Top 5">SELECT * FROM
(SELECT TOP 5 AGENT,SUM(BALANCE) AS BALANCE FROM BILLSTBL GROUP BY AGENT ORDER BY SUM(BALANCE) DESC) AS P1
UNION
SELECT * FROM
(SELECT 'OTHERS' AS AGENT,SUM(BALANCE) AS BALANCE FROM BILLSTBL
WHERE BILLSTBL.AGENT NOT IN(
SELECT T12.AGENT FROM (
SELECT TOP 5 AGENT,SUM(BALANCE) AS BALANCE FROM BILLSTBL GROUP BY AGENT ORDER BY SUM(BALANCE) DESC) AS T12)) AS P2</Query>
					<Query Name="Bottom 5">SELECT * FROM
(SELECT TOP 5 AGENT,SUM(BALANCE) AS BALANCE FROM BILLSTBL GROUP BY AGENT ORDER BY SUM(BALANCE)) AS P1
UNION
SELECT * FROM
(SELECT 'OTHERS' AS AGENT,SUM(BALANCE) AS BALANCE FROM BILLSTBL
WHERE BILLSTBL.AGENT NOT IN(
SELECT T12.AGENT FROM (
SELECT TOP 5 AGENT,SUM(BALANCE) AS BALANCE FROM BILLSTBL GROUP BY AGENT ORDER BY SUM(BALANCE)) AS T12)) AS P2</Query>
				</Filter>
				<Filter Name="Agent" FilterValueType="Query" FilterValueQuery="select distinct name from agents where name in (select agent from bills)">
					<Query>SELECT * FROM
(SELECT AGENT,SUM(BALANCE) AS BALANCE FROM BILLSTBL WHERE AGENT = '$VALUE' GROUP BY AGENT) AS P1
UNION
SELECT * FROM
(SELECT 'OTHERS' AS AGENT,SUM(BALANCE) AS BALANCE FROM BILLSTBL
WHERE BILLSTBL.AGENT NOT IN(
SELECT T12.AGENT FROM (
SELECT AGENT,SUM(BALANCE) AS BALANCE FROM BILLSTBL WHERE AGENT = '$VALUE' GROUP BY AGENT) AS T12)) AS P2</Query>
				</Filter>
			</Filters>
		</ChartType>
		<Data FilterDescription="Agent wise turn over in desending order">
			<Query>SELECT AGENT,SUM(BALANCE) AS TURNOVER FROM BILLSTBL GROUP BY AGENT ORDER BY SUM(BALANCE) DESC</Query>
		</Data>
	</Report>
	<Report Name="PendingAmount">
		<ChartType Name="BarChart">
			<Filters>
				<Filter Name="Amount Rank" FilterValueType="List">
					<Query Name="Top 5">SELECT TOP 5 [NAME] AS PARTY,SUM(BALANCE) AS BALANCE FROM BILLSTBL
INNER JOIN PARTIES ON PARTYID = ID
WHERE BILLNO NOT IN (SELECT BILLNO FROM BILLPAYMENTSTBL)
GROUP BY [NAME]
ORDER BY BALANCE DESC</Query>
					<Query Name="Top 10">SELECT TOP 10 [NAME] AS PARTY,SUM(BALANCE) AS BALANCE FROM BILLSTBL
INNER JOIN PARTIES ON PARTYID = ID
WHERE BILLNO NOT IN (SELECT BILLNO FROM BILLPAYMENTSTBL)
GROUP BY [NAME]
ORDER BY BALANCE DESC</Query>
					<Query Name="Top 15">SELECT TOP 15 [NAME] AS PARTY,SUM(BALANCE) AS BALANCE FROM BILLSTBL
INNER JOIN PARTIES ON PARTYID = ID
WHERE BILLNO NOT IN (SELECT BILLNO FROM BILLPAYMENTSTBL)
GROUP BY [NAME]
ORDER BY BALANCE DESC</Query>
					<Query Name="Bottom 15">SELECT TOP 15 [NAME] AS PARTY,SUM(BALANCE) AS BALANCE FROM BILLSTBL
INNER JOIN PARTIES ON PARTYID = ID
WHERE BILLNO NOT IN (SELECT BILLNO FROM BILLPAYMENTSTBL)
GROUP BY [NAME]
ORDER BY BALANCE</Query>
				</Filter>
			</Filters>
			<ChartType Name="LineChart" Description="Pending Amount for Party $KEY1 monthlywise">
				<Query>SELECT [NAME] AS PARTY,LEFT(CONVERT(VARCHAR,BILLDATE,9),3) AS MONTH,SUM(BALANCE) AS AMOUNT FROM BILLSTBL INNER JOIN PARTIES ON PARTYID = ID
WHERE NAME = '$KEY1'
AND BILLNO NOT IN (SELECT BILLNO FROM BILLPAYMENTSTBL)
GROUP BY [NAME],LEFT(CONVERT(VARCHAR,BILLDATE,9),3)</Query>
				<ChartType Name="DataGrid" Description="Pending Amount for Party $KEY1 for month $KEY2">
					<Data>
						<Query>SELECT BILLNO,CONVERT(VARCHAR,BILLDATE,7) AS BILLDATE,BALANCE FROM BILLSTBL INNER JOIN PARTIES ON PARTYID = ID WHERE NAME = '$KEY1' AND BILLNO NOT IN (SELECT BILLNO FROM BILLPAYMENTSTBL) AND LEFT(CONVERT(VARCHAR,BILLDATE,9),3) = '$KEY2'</Query>
					</Data>
				</ChartType>
			</ChartType>
		</ChartType>
		<ChartType Name="PieChart">
			<Filters>
				<Filter Name="Amount Rank" FilterValueType="List">
					<Query Name="Top 5">SELECT * FROM
(SELECT TOP 5 [NAME] AS PARTY,SUM(BALANCE) AS BALANCE FROM BILLSTBL
INNER JOIN PARTIES ON PARTYID = ID
WHERE BILLNO NOT IN (SELECT BILLNO FROM BILLPAYMENTSTBL)
GROUP BY [NAME]
ORDER BY BALANCE DESC) AS P1
UNION
SELECT * FROM
(SELECT 'OTHERS' AS PARTY,SUM(BALANCE) AS BALANCE FROM BILLSTBL
WHERE PARTYID NOT IN(
SELECT T12.PARTYID FROM(
SELECT TOP 5 PARTYID,SUM(BALANCE) AS BALANCE FROM BILLSTBL 
WHERE BILLNO NOT IN (SELECT BILLNO FROM BILLPAYMENTSTBL)
GROUP BY PARTYID ORDER BY BALANCE DESC) AS T12)) AS P2</Query>
					<Query Name="Top 10">SELECT * FROM
(SELECT TOP 10 [NAME] AS PARTY,SUM(BALANCE) AS BALANCE FROM BILLSTBL
INNER JOIN PARTIES ON PARTYID = ID
WHERE BILLNO NOT IN (SELECT BILLNO FROM BILLPAYMENTSTBL)
GROUP BY [NAME]
ORDER BY BALANCE DESC) AS P1
UNION
SELECT * FROM
